name: Andrew Liebchen
markdown: redcarpet
highlighter: pygments
baseurl: "http://andrewliebchen.github.io/a12n"
gems: [jekyll/timeago]
navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
